### ISSUE TITLE
Does not work in ubuntu 19.04 with gnome 3.32

### ISSUE THREAD

**Issue by lakinduakash** [hedayaty/NetSpeed#92]

**Comment by aicherm** [comment]
My logs during extension reload:

`gnome-software[3548]: State change on user/*/*/shell-extension/netspeed_hedayaty.gmail.com/* from installed to available is not OK
gnome-shell[2202]: Extension "netspeed@hedayaty.gmail.com" had error: TypeError: this._construct is not a function
gnome-software[3548]: State change on user/*/*/shell-extension/netspeed_hedayaty.gmail.com/* from available to installed is not OK
gnome-software[3548]: netspeed_hedayaty.gmail.com has error: TypeError: this._construct is not a function
`

**Comment by lakinduakash** [comment]
Can you tell how to obtain gnome shell extensions log?

**Comment by Fubuchi** [comment]
On Manjaro with Gnome 3.32, uninstall and reinstall extension make it work UNTIL THE NEXT REBOOT, then you need to do the above step again. Considering use it as a temporary work around.

**Comment by hedayaty** [comment]
After upgrade to FC 30 with gnome 3.32, even fixing the js issues the extension does not work for me!
I have holding the fixes until I figure out what is wrong.

**Comment by hedayaty** [comment]
I realized the extensions were disabled!
This version should work for everyone. Either try the master or get from gnome(it may take a while till they approve)

**Comment by gendarius** [comment]
Tried both from Gnome and from the master, still not working for me.
Using dconf in org/gnome/shell/enabled-extensions I correctly see ['netspeed@hedayaty.gmail.com']

**Comment by lakinduakash** [comment]
I don't know the reason. The extension is started to work suddenly recently. :p
