### ISSUE TITLE
Doesn't work in Gnome 3.34.1, Fedora 31

### ISSUE THREAD

**Issue by digaev** [hedayaty/NetSpeed#112]
After upgrading to Fedora 31 the extension stopped working. Tried to reinstall but it didn't help. Gnome 3.34.1.
```
JS ERROR: Extension netspeed@hedayaty.gmail.com: TypeError: this.update_ui is not a function
LayoutMenuItem@/home/nick/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/layout_menu_item.js:50:9
_init@/home/nick/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/net_speed_status_icon.js:86:28
enable@/home/nick/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/net_speed.js:313:29
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:131:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:99:13
```

**Comment by digaev** [comment]
Seems like the problem was with the Dash To Panel extension, upgrading to the latest version fixed the issue.

**Comment by hedayaty** [comment]
That's exactly the platform I use. Pretty sure it works!
